import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import icon from '../img/logo.png'
import styles from '../../styles/Home.module.css'
import cstyles from '../../styles/Contact.module.css'
import { BiHomeSmile, BiWinkSmile, BiFolderOpen, BiMailSend, BiEnvelope, BiPhone } from 'react-icons/bi';

export default function Contact() {
    if (typeof window !== "undefined") {

        window.onload=function(){
        var form = document.getElementById('sheetdb-form');
        form.addEventListener("submit", e => {
            e.preventDefault();
            fetch(form.action, {
                method : "POST",
                body: new FormData(document.getElementById("sheetdb-form")),
            }).then(
                response => response.json()
            ).then((html) => {
            // you can put any JS code here
            

            setTimeout(function (){
                alert("Thank you for messaging! I will get in touch with you shortly.");
                form.reset();
            }
                , 1000);
            });
        });
    }
    }

    return (
      
    <>
    
     <div className={styles.container}>
      <Head>
        <title>Next JS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
        <link rel="shortcut icon" href={icon} type="image/x-icon" />
      </Head>
      <header>
        <nav className={styles.navigation}>
        
          <div className={styles.navLink}>
            <Link href="/">
              <a alt="Home"><BiHomeSmile size={30} /></a>
            </Link>
            <Link href="/posts/about">
              <a alt="About"><BiWinkSmile size={30}/></a>
            </Link>
            <Link href="/">
              <a alt="Logo"> 
                <Image src={icon} 
                  alt="banner"
                  width={40}
                  height={40}/>
              </a>
            </Link>
            <Link href="/posts/portfolio">
              <a alt="Projects"><BiFolderOpen size={30}/></a>
            </Link>
            <Link href="/posts/contact">
              <a alt="Contact"><BiMailSend size={30}/></a>
            </Link>
          </div>
        </nav>
      </header>

      <main className={cstyles.contact}>
          <div className={cstyles.form}>
            <h1>Get in Touch!</h1>
            {/* <h1>Contact Form</h1> */}
            <form className={styles.grid} method="POST" action="https://sheetdb.io/api/v1/258k3v1xk5ke6" id="sheetdb-form">      
                <input name="Name" type="text" className={cstyles.feedback} placeholder="Name" required/>   
                <input name="Email" type="email" className={cstyles.feedback} placeholder="Email" required/>
                <textarea name="Message" type="text" className={cstyles.textarea} placeholder="Message"></textarea>
                <input className={cstyles.submit} type="submit" value="SUBMIT" id="googleSheet"/>
                <div id="submitSuccess" className={cstyles.submitSuccess}>Thank you for messaging! I will get in touch with you shortly.</div>
            </form>
          </div>
        
        <div className={cstyles.contactDetails}>
            <address className={cstyles.address}>
                <div>
                    <h1><BiEnvelope size={25} viewBox="0 0 25 16"/> Email Address:</h1>
                    <a href="mailto:christafayereyes@gmail.com">christafayereyes@gmail.com</a>
                </div>
                <div>
                    <h1><BiPhone size={25} viewBox="0 0 25 16"/> Contact Number:</h1>
                    <a href="tel:+14313881246">+1(431) 388-1246</a>
                </div>
                
            </address>
        </div>
      </main>
      

      <footer className={styles.footer}>
          Copyright | {' '} Christa Faye Reyes © 2022  {' '} 
          <span className={styles.logo}>
            <Image src={icon} alt="Logo" width={15} height={15}/>
          </span>
      </footer>

    </div>
    </>
  )
}