import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import icon from './img/logo.png'
import styles from '../styles/Home.module.css'
import { BiHomeSmile, BiWinkSmile, BiFolderOpen, BiMailSend } from 'react-icons/bi';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header>
        <nav className={styles.navigation}>
        
          <div className={styles.navLink}>
            <Link href="/">
              <a alt="Home"><BiHomeSmile size={30} /></a>
            </Link>
            <Link href="/posts/about">
              <a alt="About"><BiWinkSmile size={30}/></a>
            </Link>
            <Link href="/">
              <a alt="Logo"> 
                <Image src={icon} 
                  alt="banner"
                  width={40}
                  height={40}/>
              </a>
            </Link>
            <Link href="/posts/portfolio">
              <a alt="Projects"><BiFolderOpen size={30}/></a>
            </Link>
            <Link href="/posts/contact">
              <a alt="Contact"><BiMailSend size={30}/></a>
            </Link>
          </div>
        </nav>
      </header>
      <main className={styles.main}>
        
        <div>
          <span className={styles.title}>Hi, I am <Link href="/posts/about"><a className={styles.name}>Christa Faye.</a></Link></span>
          <h3 className={styles.description}>System Analyst | Web Designer | Graphic Artist</h3>
        </div>

        <div className={styles.grid}>
        <Link href="/posts/portfolio">
          <a alt="Projects" className={styles.card}>
            <h2>PROJECTS</h2>
            <p>Have a glance of my works. </p>
          </a>
          </Link>
          <Link href="/posts/contact">
          <a alt="Contact" className={styles.card}>
            <h2>CONTACT</h2>
            <p>I will be glad to assist you.</p>
          </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
          Copyright | {' '} Christa Faye Reyes © 2022  {' '} 
          <span className={styles.logo}>
            <Image src={icon} alt="Logo" width={15} height={15}/>
          </span>
      </footer>
    </div>
  )
}
